Exposys Data Labs - Data Science Project

In [ ]:
# Importing libraries

import numpy as np
import pandas as pd

In [ ]:
# Loading Data

dataset = pd.read_csv("/content/drive/MyDrive/Copy of 50_Startups.csv")
print("Dataset.head() \n ", dataset.head())

Dataset.head() 
     R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94


In [ ]:
# Checking the size of the Dataset

print("Dataset Info: \n")
print(dataset.info())

Dataset Info: 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   Profit           50 non-null     float64
dtypes: float64(4)
memory usage: 1.7 KB
None


In [ ]:
# Input values

x = dataset.iloc[:, :-1].values
print("First 10 Spend Values : \n", x[0:10, :])

First 10 Spend Values : 
 [[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]]


In [ ]:
# Input values
x = dataset.iloc[:, :-1].values
print("First 10 Spend Values: \n", x[0:10, :])


# Output values
y = dataset.iloc[:, 3].values
y1 = y
y1 = y1.reshape(-1, 1)
print("\nFirst 10 Profit Values: \n", y1[0:10, :])

First 10 Spend Values: 
 [[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]]

First 10 Profit Values: 
 [[192261.83]
 [191792.06]
 [191050.39]
 [182901.99]
 [166187.94]
 [156991.12]
 [156122.51]
 [155752.6 ]
 [152211.77]
 [149759.96]]


In [ ]:
# Splitting the data into training and testing data
# Training : Testing = 80 : 20

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Here, I'm using Multi Linear Regression for Feature Scaling


# Fitting Multi Linear regression model to Training model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(xtrain, ytrain)

# Predicting the testing set results
y_pred = regressor.predict(xtest)

y_pred1 = y_pred
y_pred1 = y_pred1.reshape(-1,1)

print("Results for Linear Regression Prediction: ")
print ("\nFirst 10 Predicted value : \n", y_pred1[0:10, :])

Results for Linear Regression Prediction: 

First 10 Predicted value : 
 [[103901.8969696 ]
 [132763.05993126]
 [133567.90370044]
 [ 72911.78976736]
 [179627.92567224]
 [115166.64864795]
 [ 67113.5769057 ]
 [ 98154.80686776]
 [114756.11555221]
 [169064.01408795]]
